###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/31

###
GET http://localhost:3000/api/v1/users/search?q=edu

###
DELETE http://localhost:3000/api/v1/users/1

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "firstName": "Moshe",
    "lastName": "Plotkin",
    "email": "plotkinm@newpaltz.edu"
}

###
PATCH http://localhost:3000/api/v1/users/31
Content-Type: application/json

{
    "firstName": "Prof. Moshe"
}